[platformio]
default_envs = syncstreamer
build_dir = /mnt/Sam/Builds/syncstreamer

[env:syncstreamer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino, espidf
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_speed = 921600
; monitor_filters = esp32_exception_decoder
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=32
    -DCONFIG_LWIP_UDP_RECVMBOX_SIZE=12
    -DCONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64
    -DCONFIG_ESP_MAIN_TASK_AFFINITY_CPU0=1
lib_deps =
    ayushsharma82/ElegantOTA@^3.1.7
    esp32async/AsyncTCP@^3.3.7
    knolleary/PubSubClient@^2.8

